### ISSUE TITLE
All output fail when one kafka output fails

### ISSUE THREAD

**Issue by tomouki** [logstash-plugins/logstash-output-kafka#183] opened 2018-04-05 05:38 UTC
- Version: 6.2.1
- Operating System: Centos

I have several output in logstash and the config file is as follows.
<pre> 
input {
    redis{ ... }
}
filter {... }
output { 
    file { ... }
    http { ... }
    jdbc { ... }
    kafka { 
        bootstrap_servers => "host1:6667,host2:6667"
        codec => json {}
        topic_id => "test1"
        acks => "0"
        retries => 1
        metadata_fetch_timeout_ms => 5000
        metadata_max_age_ms => 5000
        reconnect_backoff_ms => 1000
        request_timeout_ms => "5000"
    }
 }</pre>

When all kafka broker down, other output (file, http, jdbc) is stopped. can't get any event from redis
If the "retries" value is greater than 0, is event not dropping?
Is there a way not to affect other outputs?

there is LS error log.. The following logs are continuously output.
<pre>
[2018-04-05T14:20:40,405][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Node -2 disconnected.
[2018-04-05T14:20:40,405][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Connection to node -2 could not be established. Broker may not be available.
[2018-04-05T14:20:40,405][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initialize connection to node host1:6667 (id: -1 rack: null) for sending metadata request
[2018-04-05T14:20:40,405][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initiating connection to node host1:6667 (id: -1 rack: null)
[2018-04-05T14:20:40,406][DEBUG][org.apache.kafka.common.network.Selector] [Producer clientId=producer-1] Connection with host1/xxx.xxx.xxx.xxx disconnected
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_121]
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:444) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:398) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2018-04-05T14:20:40,406][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Node -1 disconnected.
[2018-04-05T14:20:40,406][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Connection to node -1 could not be established. Broker may not be available.
[2018-04-05T14:20:40,406][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Give up sending metadata request since no node is available
[2018-04-05T14:20:41,406][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initialize connection to node host1:6667 (id: -1 rack: null) for sending metadata request
[2018-04-05T14:20:41,406][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initiating connection to node host1:6667 (id: -1 rack: null)
[2018-04-05T14:20:41,407][DEBUG][org.apache.kafka.common.network.Selector] [Producer clientId=producer-1] Connection with host1/xxx.xxx.xxx.xxx disconnected
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_121]
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:444) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:398) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2018-04-05T14:20:41,407][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Node -1 disconnected.
[2018-04-05T14:20:41,407][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Connection to node -1 could not be established. Broker may not be available.
[2018-04-05T14:20:41,407][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initialize connection to node host2:6667 (id: -2 rack: null) for sending metadata request
[2018-04-05T14:20:41,407][DEBUG][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Initiating connection to node host2:6667 (id: -2 rack: null)
[2018-04-05T14:20:41,408][DEBUG][org.apache.kafka.common.network.Selector] [Producer clientId=producer-1] Connection with host2/xxx.xxx.xxx.xxx disconnected
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_121]
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106) ~[kafka-clients-1.0.0.jar:?]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:444) [kafka-clients-1.0.0.jar:?]
</pre>

**Comment by nerophon** [comment] 2020-12-11 11:05
This is by design. Outputs are executed sequentially, and if one hangs the others will also hang. There are therefore two recommendations we can offer:
1. separate the outputs into different pipelines
2. use the pipeline-to-pipeline feature to back each output with its own persistent queue to handle backpressure; this pattern is described here https://www.elastic.co/guide/en/logstash/current/pipeline-to-pipeline.html#output-isolator-pattern. Note however that this feature is only stable in the 7.x series, and was in beta till 7.4. We don't recommend using it in earlier versions in production.

**Comment by roaksoax** [comment] 2021-03-04 20:45
Based on the above comment, I'm closing this issue.

**Closed by roaksoax** 2021-03-04 20:45 UTC
